#! /usr/bin/env python


"""jarvis: CLI executable script"""


import argparse


def main():
    parser = argparse.ArgumentParser(description="Jarvis manager")
    args = parser.parse_args()


if __name__ == "__main__":
    main()
